[package]
name = "lignum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
fastrand = "2.0.1"
ggegui = "0.4.0"
ggez = "0.9.3"
rayon = "1.8.1"
